# @package _global_
model:
  _target_: src.models.apid.APID
  name: apid

  # Conditional APIDs hparams
  dim_u: 2            # latent noise dimensionality
  n_trans: 15         # Number of residual tranformations per ResidualNF layer
  tol: 1e-4
  aug_mode: s         # s - sampling;  q - quantiles
  n_quantiles: 32     # number of quantiles, if aug_mode == 'q'
  eps: 0.5            # variance of the augmentation

  # Training hparams
  batch_size: 32
  burn_in_epochs: 500 # burn-in stage
  q_epochs: 100       # query stage
  curv_epochs: 500    # query-curvature stage
  noise_std: 0.001    # noise regularization
  lr: 1e-2            # learning rate
  cf_only: True       # Trainining only counterfactual transformations
  ema_q: 0.99         # EMA of weights for evaluating the query

  # Loss coefficients
  q_coeff: 2.0        # lambda_Q coefficient
  curv_coeff: 0.0     # lambda_kappa coefficient

